config/routes.rb
Rails.application.routes.draw do
    # error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'trips-choice', to: 'trips#trip_choice'
  get 'trips-category', to: 'trips#trip_category'
  resources :trips
  resources :bookings, only: [:index, :create, :show, :destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :trip
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :skip_authorization, only: %i[index show]
  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    @markers = [{
      lat: @booking.trip.latitude,
      lng: @booking.trip.longitude,
      info_window: render_to_string(partial: "info_window_show", locals: { trip: @booking }),
    },
                {
                  lat: @booking.trip.stop_1_lat,
                  lng: @booking.trip.stop_1_long,
                  info_window: render_to_string(partial: "info_window2", locals: { trip: @booking }),
                },
                {
                  lat: @booking.trip.stop_2_lat,
                  lng: @booking.trip.stop_2_long,
                  info_window: render_to_string(partial: "info_window3", locals: { trip: @booking }),
                }]
  end

  def new
    @booking = Booking.new
  end

  def create
    @trip = Trip.find(params[:booking][:trip_id])
    @booking = Booking.new(booking_params)
    @booking.schedule_date = get_booking_date(booking_params)
    authorize @booking
    @booking.user = current_user
    if @booking.save
      flash[:notice] = 'Booking has been successfully recorded'
      redirect_to bookings_path
    else
      render 'trips/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @trip = Trip.find(@booking.trip_id)
    authorize @booking
    if Booking.delete(params[:id]).positive?
      flash[:success] = 'Booking has been cancelled'
    else
      flash[:error] = 'Sorry something went wrong, please try again'
    end
    redirect_to bookings_path
  end

  private

  def get_booking_date(params)
    "#{params["schedule_date(3i)"]}/#{params["schedule_date(2i)"]}/#{params["schedule_date(1i)"]}"
  end

  def booking_params
    params.require(:booking).permit(:total_price, :schedule_date, :trip_id)
  end
end

app/views/bookings/_info_window2.html.erb
<% if !@booking.trip.stop_1.nil? %>
<p><%= @booking.trip.stop_1 %></p>
  <%= image_tag(@booking.trip.stop_1_img_url, height: '200px', width: '200px', style: "border-radius: 20px;") %>
<% end %>

app/views/bookings/_info_window3.html.erb
<% if !@booking.trip.stop_2.nil? %>
    <p><%= @booking.trip.stop_2 %></p>
    <%= image_tag(@booking.trip.stop_2_img_url, height: '200px', width: '200px', style: "border-radius: 20px;") %>
<% end %>

app/views/bookings/_info_window_show.html.erb
<h2><%= @booking.trip.name %></h2>
<p><%= @booking.trip.address %></p>
<%= image_tag(@booking.trip.image_url, height: '200px', width: '200px', style: "border-radius: 20px;") %>

app/views/bookings/index.html.erb
<div class="col-sm-12 d-flex justify-content-center">
  <h1 id="bookingtitle" class= "px-3 py-1">My Trip list</h1>
</div>

<div class="bookingcards d-flex row justify-content-center mx-0">
  <% @bookings.each do |booking| %>
    <% if (booking.user_id == current_user.id) %>
      <div class="booking card" style="width: 18rem;">
        <div class="card-header d-flex justify-content-center">
          <%= link_to booking_path(booking) do %>
            <h5 class="card-title fw-bolder"><%= booking.trip.name %> </h5>
          <% end %>
        </div>
        <div class="card-body d-flex justify-content-center ">
          <ul class="list-group list-group-flush">
            <li class="list-group-item"> <strong>Location:</strong> <%= booking.trip.address %></li>
            <li class="list-group-item"> <strong>Schedule date:</strong> <%= booking.schedule_date %></li>
            <li class="list-group-item"> <strong>Tour guide price:</strong> Rs<%= booking.trip.price.to_i %></li>
            <li class="list-group-item p-0 pt-2 text-center">
              <%= link_to booking_path(booking), method: :delete do %> 
               <i class="fas fa-trash-alt"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="d-flex flex-wrap justify-content-center w-100 text-center m-0">
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.js"></script>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.css" type="text/css">
    <h3 id="title"  class= "px-4 py-2" >
       Your trip to <%= @booking.trip.name %>
    </h3>
    <div id="map"
        style="width: 100%; height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>